// import type { Metadata } from "next";
import CustomNavbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-screen flex flex-col">
        <CustomNavbar />
        <main className="grow">{children}</main>
        <Footer />
      </div>
    </>
  );
}
