import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Vazir = localFont({
  src: [
    {
      path: "./fonts/Vazir-Thin-FD-WOL.woff2",
      weight: "200",
    },
    {
      path: "./fonts/Vazir-Light-FD-WOL.woff2",
      weight: "300",
    },
    {
      path: "./fonts/Vazir-FD-WOL.woff2",
      weight: "400",
    },
    {
      path: "./fonts/Vazir-Medium-FD-WOL.woff2",
      weight: "500",
    },
    {
      path: "./fonts/Vazir-Bold-FD-WOL.woff2",
      weight: "700",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${Vazir.className} antialiased`}>
        <Providers>
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
